#!/bin/bash
# Tuner-UI Docker Setup Script
# This script generates required secrets and creates the .env file

set -e

echo "=== Tuner-UI Docker Setup ==="
echo ""

# Check if .env already exists
if [ -f ".env" ]; then
    echo "WARNING: .env file already exists!"
    read -p "Do you want to overwrite it? (y/N) " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Aborted. Please edit .env manually or remove it first."
        exit 1
    fi
fi

# Check for required tools
if ! command -v openssl &> /dev/null; then
    echo "ERROR: openssl is required but not installed."
    exit 1
fi

if ! command -v python3 &> /dev/null && ! command -v python &> /dev/null; then
    echo "ERROR: python is required but not installed."
    exit 1
fi

# Determine python command
PYTHON_CMD="python3"
if ! command -v python3 &> /dev/null; then
    PYTHON_CMD="python"
fi

echo "Generating secrets..."

# Generate secrets
POSTGRES_PASSWORD=$(openssl rand -hex 16)
SECRET_KEY=$(openssl rand -hex 32)
ENCRYPTION_KEY=$($PYTHON_CMD -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())" 2>/dev/null || echo "GENERATE_MANUALLY")

if [ "$ENCRYPTION_KEY" = "GENERATE_MANUALLY" ]; then
    echo "WARNING: Could not generate encryption key automatically."
    echo "Please install cryptography: pip install cryptography"
    echo "Then generate manually: python -c \"from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())\""
    ENCRYPTION_KEY="REPLACE_WITH_GENERATED_KEY"
fi

# Prompt for Tinker API key
echo ""
read -p "Enter your Tinker API Key (or press Enter to skip): " TINKER_API_KEY
if [ -z "$TINKER_API_KEY" ]; then
    TINKER_API_KEY="your_tinker_api_key_here"
    echo "WARNING: You need to add your Tinker API key to .env before running"
fi

# Create .env file
cat > .env << EOF
# Tuner-UI Docker Environment Configuration
# Generated by docker-setup.sh on $(date)

# ===== API Keys =====
TINKER_API_KEY=$TINKER_API_KEY

# ===== Security (auto-generated) =====
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
SECRET_KEY=$SECRET_KEY
ENCRYPTION_KEY=$ENCRYPTION_KEY

# ===== Frontend Configuration =====
NEXT_PUBLIC_API_BASE_URL=http://localhost:8000

# ===== Backend Configuration =====
CORS_ORIGINS=http://localhost:3000,http://localhost:80
LOG_LEVEL=INFO
ENVIRONMENT=production
EOF

echo ""
echo "=== Setup Complete ==="
echo ""
echo ".env file created with generated secrets."
echo ""
echo "Next steps:"
echo "  1. Edit .env and add your TINKER_API_KEY if you haven't"
echo "  2. Run: docker-compose up -d"
echo "  3. Access: http://localhost:3000"
echo ""
echo "To view logs: docker-compose logs -f"
echo "To stop: docker-compose down"
